### ISSUE TITLE
Difficulty getting react-gridstack up and running

### ISSUE THREAD

**Issue by 27pchrisl** [pitrho/react-gridstack#3]
Hi,

I'm having difficulty getting started with this module. I have created a very small project to try and run the example in README.md but am getting the console error:

`Uncaught TypeError: (0 , _jquery2.default)(...).gridstack is not a function`

I've attached a zip of the small project that is causing the error. Is there a problem with the way I am importing this in index.js or webpack.config.js?

[t22.zip](https://github.com/pitrho/react-gridstack/files/494050/t22.zip)

Thanks!
- Chris

**Comment by nerdess** [comment]
got the same issue, described it here already [Uncaught TypeError: (0 , _jquery2.default)(...).gridstack is not a function](https://github.com/troolee/gridstack.js/issues/618)
